fix message lost
kubeedge/beehive pull request #8
Opened 2019-05-15 07:42 UTC by edisonxiang

Currently the `Send2Group` function will lost message when the channel is full.
Actually we need to wait for the idle channel so that we will not lose messages.

2019-05-15 07:44 UTC, m1093782566 commented
I feel shocked about it

cc @qizha @CindyXing thoughts?

2019-05-15 08:09 UTC, edisonxiang commented
The logs are put here.
https://gist.github.com/edisonxiang/e249aef7378b9b51f2e2c4f0783c595f
In this test, we try to send 100 pod creating messages to cloudhub.
At last, only 90 pod creating messages are return.
10 of them are lost.
We also need to remove this line of code.
https://github.com/kubeedge/kubeedge/blob/master/cloud/pkg/cloudhub/channelq/channelq.go#L95

Once this pr is approved, I will submit another pr in the kubeedge/kubeedge repository.

2019-05-15 16:03 UTC, sids-b commented
@edisonxiang , does commenting the default case solve the issue ? I think we will have to remove the entire select block.

2019-05-15 17:11 UTC, CindyXing requested changes
The case/default is one of the ways to know whether a go channel buffer is full. 
Instead of removing the default logging, we should add retry logic. 

My suggestion is to compare the current channel length with the cap limit and add retry.

2019-05-15 17:12 UTC, CindyXing commented
Glad to see perf validation found good issue.

2019-05-16 04:26 UTC, edisonxiang commented
@sids-b we should not remove `select`.
The `select` blocks until one of its cases can run, then it executes that case.
Actually the `select` 'case' will wait util the channel has idle buffer and then will continue to run.

2019-05-16 04:32 UTC, edisonxiang commented
@CindyXing Thanks. IMO. Actually the `select case` will wait util the channel has idle buffer and then will continue to run. but currently because the `default` is existing so that `default` will be run and the message lost. Actually `select case` is always waiting for retry once the channel has idle buffer.
So I suggest to just remove default. How about your ideas?

I tried to remove 'default' here in beehive and `default` in kubeege https://github.com/kubeedge/kubeedge/blob/master/cloud/pkg/cloudhub/channelq/channelq.go#L95

In the performance tests it works, no message is lost.

2019-05-16 05:14 UTC, sids-b commented
@edisonxiang , I think just ```go ch <- message ``` will also block the go routing till the buffer is empty ??

2019-05-16 05:32 UTC, sids-b commented
@edisonxiang We can update our vendor with the latest beehive and the fix you suggested in dispatch once this PR is merged

2019-05-16 06:16 UTC, edisonxiang commented
@sids-b Got it. Thanks

2019-05-16 10:45 UTC, sids-b approved these changes
LGTM

2019-05-16 13:33 UTC, sids-b commented
@edisonxiang , lets us implement like @CindyXing 's suggestions. We need to know that the channel was full, this way we can find out how many times beehive had to retry to send the message and if they number is big, we can think of adding buffered channels. Thoughts ??

2019-05-16 18:27 UTC, CindyXing commented
> @CindyXing Thanks. IMO. Actually the `select case` will wait util the channel has idle buffer and then will continue to run. but currently because the `default` is existing so that `default` will be run and the message lost. Actually `select case` is always waiting for retry once the channel has idle buffer.
> So I suggest to just remove default. How about your ideas?
> 
> I tried to remove `default` here in beehive and `default` in kubeege https://github.com/kubeedge/kubeedge/blob/master/cloud/pkg/cloudhub/channelq/channelq.go#L95
> 
> In the performance tests it works, no message is lost.

Edison, you can use the len and cap function against a golang channel to check whether it is full and enable retry logic.

2019-05-16 18:28 UTC, CindyXing commented
I suggest label this issue as a "good first issue". Don't have permission to do so though. 
Glad to see perf finding some bug that normal test wouldn't. Thanks.

2019-05-17 02:15 UTC, edisonxiang commented
@CindyXing @sids-b The commit is updated.
Please take a look again. Thanks.
Actually i am a little worried about the retry interval (e.g. 10 ms)
I am not sure whether it will affect the performace.

I prefer another modification like below if we need to record the logs about `the channel is full`

```
		select {
		case ch <- message:
		default:
			log.LOGGER.Warnf("the message channel is full, message: %+v", message)
		        select {
		        case ch <- message:
                        }
		}
```

What about your ideas? @CindyXing @sids-b

2019-05-18 12:46 UTC, sids-b commented
@edisonxiang , the modifiction which you suggested looks good to me. time.Sleep may affect the performance.

2019-05-20 01:20 UTC, edisonxiang commented
@sids-b Thanks, Let's wait for the suggestion from @CindyXing

2019-06-03 10:41 UTC, rohitsardesai83 approved these changes
lgtm

2019-06-03 10:43 UTC, rohitsardesai83 commented
@m1093782566 , @edisonxiang , can we merge this code fix  and test whether it fixes https://github.com/kubeedge/kubeedge/issues/488

2019-06-03 10:57 UTC, m1093782566 commented
/lgtm

2019-06-03 19:42 UTC, sids-b commented
Lets try if this fix solves the message lost problem. @edisonxiang can you please update the vendor in kubeedge repo ?

2019-06-03 19:42 UTC, merged

2019-06-05 01:39 UTC, edisonxiang commented
@sids-b sorry for late. I will update later. Thanks.